package com.lyl.outsourcing.activity.dao.mapper;

import com.lyl.outsourcing.activity.entity.RaffleRecord;
import com.lyl.outsourcing.activity.entity.RaffleRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RaffleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    long countByExample(RaffleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    int deleteByExample(RaffleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    int insert(RaffleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    int insertSelective(RaffleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    List<RaffleRecord> selectByExample(RaffleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RaffleRecord record, @Param("example") RaffleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RaffleRecord record, @Param("example") RaffleRecordExample example);
}