package com.lyl.outsourcing.activity.dao.mapper;

import com.lyl.outsourcing.activity.entity.Raffle;
import com.lyl.outsourcing.activity.entity.RaffleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RaffleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    long countByExample(RaffleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int deleteByExample(RaffleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int insert(Raffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int insertSelective(Raffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    List<Raffle> selectByExample(RaffleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    Raffle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Raffle record, @Param("example") RaffleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Raffle record, @Param("example") RaffleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Raffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_raffle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Raffle record);
}