package com.lyl.outsourcing.activity.entity;

import java.io.Serializable;
import java.util.Date;

public class Material implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.file_length
     *
     * @mbg.generated
     */
    private Long fileLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.content_type
     *
     * @mbg.generated
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.properties
     *
     * @mbg.generated
     */
    private String properties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_material.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_material
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.id
     *
     * @return the value of r_material.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.id
     *
     * @param id the value for r_material.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.type
     *
     * @return the value of r_material.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.type
     *
     * @param type the value for r_material.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.name
     *
     * @return the value of r_material.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.name
     *
     * @param name the value for r_material.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.path
     *
     * @return the value of r_material.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.path
     *
     * @param path the value for r_material.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.file_length
     *
     * @return the value of r_material.file_length
     *
     * @mbg.generated
     */
    public Long getFileLength() {
        return fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.file_length
     *
     * @param fileLength the value for r_material.file_length
     *
     * @mbg.generated
     */
    public void setFileLength(Long fileLength) {
        this.fileLength = fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.content_type
     *
     * @return the value of r_material.content_type
     *
     * @mbg.generated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.content_type
     *
     * @param contentType the value for r_material.content_type
     *
     * @mbg.generated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.properties
     *
     * @return the value of r_material.properties
     *
     * @mbg.generated
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.properties
     *
     * @param properties the value for r_material.properties
     *
     * @mbg.generated
     */
    public void setProperties(String properties) {
        this.properties = properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_material.create_time
     *
     * @return the value of r_material.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_material.create_time
     *
     * @param createTime the value for r_material.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}