package com.lyl.outsourcing.activity.entity;

import java.io.Serializable;
import java.util.Date;

public class RaffleRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.raffle_id
     *
     * @mbg.generated
     */
    private Long raffleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.raffle_item_id
     *
     * @mbg.generated
     */
    private Long raffleItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.raffle_time
     *
     * @mbg.generated
     */
    private Date raffleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_record.achieve_time
     *
     * @mbg.generated
     */
    private Date achieveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_raffle_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.open_id
     *
     * @return the value of act_raffle_record.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.open_id
     *
     * @param openId the value for act_raffle_record.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.raffle_id
     *
     * @return the value of act_raffle_record.raffle_id
     *
     * @mbg.generated
     */
    public Long getRaffleId() {
        return raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.raffle_id
     *
     * @param raffleId the value for act_raffle_record.raffle_id
     *
     * @mbg.generated
     */
    public void setRaffleId(Long raffleId) {
        this.raffleId = raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.raffle_item_id
     *
     * @return the value of act_raffle_record.raffle_item_id
     *
     * @mbg.generated
     */
    public Long getRaffleItemId() {
        return raffleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.raffle_item_id
     *
     * @param raffleItemId the value for act_raffle_record.raffle_item_id
     *
     * @mbg.generated
     */
    public void setRaffleItemId(Long raffleItemId) {
        this.raffleItemId = raffleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.name
     *
     * @return the value of act_raffle_record.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.name
     *
     * @param name the value for act_raffle_record.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.description
     *
     * @return the value of act_raffle_record.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.description
     *
     * @param description the value for act_raffle_record.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.state
     *
     * @return the value of act_raffle_record.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.state
     *
     * @param state the value for act_raffle_record.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.raffle_time
     *
     * @return the value of act_raffle_record.raffle_time
     *
     * @mbg.generated
     */
    public Date getRaffleTime() {
        return raffleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.raffle_time
     *
     * @param raffleTime the value for act_raffle_record.raffle_time
     *
     * @mbg.generated
     */
    public void setRaffleTime(Date raffleTime) {
        this.raffleTime = raffleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_record.achieve_time
     *
     * @return the value of act_raffle_record.achieve_time
     *
     * @mbg.generated
     */
    public Date getAchieveTime() {
        return achieveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_record.achieve_time
     *
     * @param achieveTime the value for act_raffle_record.achieve_time
     *
     * @mbg.generated
     */
    public void setAchieveTime(Date achieveTime) {
        this.achieveTime = achieveTime;
    }
}