package com.lyl.outsourcing.activity.entity;

import java.io.Serializable;

public class RaffleItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.raffle_id
     *
     * @mbg.generated
     */
    private Long raffleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.price
     *
     * @mbg.generated
     */
    private Boolean price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_raffle_item.total_num
     *
     * @mbg.generated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_raffle_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.id
     *
     * @return the value of act_raffle_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.id
     *
     * @param id the value for act_raffle_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.raffle_id
     *
     * @return the value of act_raffle_item.raffle_id
     *
     * @mbg.generated
     */
    public Long getRaffleId() {
        return raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.raffle_id
     *
     * @param raffleId the value for act_raffle_item.raffle_id
     *
     * @mbg.generated
     */
    public void setRaffleId(Long raffleId) {
        this.raffleId = raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.name
     *
     * @return the value of act_raffle_item.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.name
     *
     * @param name the value for act_raffle_item.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.description
     *
     * @return the value of act_raffle_item.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.description
     *
     * @param description the value for act_raffle_item.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.price
     *
     * @return the value of act_raffle_item.price
     *
     * @mbg.generated
     */
    public Boolean getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.price
     *
     * @param price the value for act_raffle_item.price
     *
     * @mbg.generated
     */
    public void setPrice(Boolean price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_raffle_item.total_num
     *
     * @return the value of act_raffle_item.total_num
     *
     * @mbg.generated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_raffle_item.total_num
     *
     * @param totalNum the value for act_raffle_item.total_num
     *
     * @mbg.generated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }
}